dbmdz/digitalcollections-model

dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/DigitalCollectionsModelModule.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/CollectionMixIn.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/resource/ApplicationFileResourceMixIn.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/resource/AudioFileResourceMixIn.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/resource/ImageFileResourceMixIn.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/resource/TextFileResourceMixIn.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/resource/VideoFileResourceMixIn.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/entity/Article.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/entity/Collection.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/resource/ApplicationFileResource.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/resource/AudioFileResource.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/resource/ImageFileResource.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/resource/TextFileResource.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/resource/VideoFileResource.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/entity/ArticleImpl.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/entity/CollectionImpl.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/resource/ApplicationFileResourceImpl.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/resource/AudioFileResourceImpl.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/resource/ImageFileResourceImpl.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/resource/TextFileResourceImpl.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/resource/VideoFileResourceImpl.java

file resource types for coming file uploads

Fileresources

---

.gitignore
.travis.yml
README.md
dc-model-jackson/pom.xml
dc-model/pom.xml
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/entity/enums/EntityType.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/resource/MimeType.java
dc-model/src/main/java/de/digitalcollections/model/api/paging/PageResponse.java
dc-model/src/main/java/de/digitalcollections/model/api/view/HighlightingRectangle.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/parts/structuredcontent/LocalizedStructuredContentImpl.java
pom.xml

PR introduces new 2.0.0 release.

WIP: Release 2.0.0

---

README.md
dc-model/pom.xml

This PR fixes a security alert.

Fix security alert

---

dc-model/src/test/java/de/digitalcollections/model/api/identifiable/resource/MimeTypeTest.java

Add tests for mimetype from filename

---

dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/entity/parts/WebpageFactory.java
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/v1/identifiable/entity/parts/V1WebpageTest.java

for v1 test (comparing to static json) I removed created and lastmodified (set to null)

Add unit test for localdatetime de- and serialization

---

dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/DigitalCollectionsModelModule.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/resource/FileResourceMixIn.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/resource/LinkedDataFileResourceMixIn.java
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/resource/LinkedDataFileResourceTest.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/resource/LinkedDataFileResource.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/resource/LinkedDataFileResourceImpl.java
dc-model/src/main/resources/dc.mime.types

makes it possible to attach a linked data resource to an object

FileResource type for linked data

---

dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/parts/structuredcontent/ContentBlockMixIn.java
dc-model-xml/src/main/java/de/digitalcollections/model/xml/xstream/DigitalCollectionsXStreamMarshaller.java
dc-model-xml/src/main/java/de/digitalcollections/model/xml/xstream/v1/V1DigitalCollectionsXStreamMarshaller.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/parts/structuredcontent/contentblocks/HorizontalRule.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/parts/structuredcontent/contentblocks/HorizontalRuleImpl.java

This PR adds stuff needed for horizontal rules to work correctly.

Add horizontal rule and table aliases

---

dc-model-jackson/pom.xml
dc-model-xml/pom.xml
dc-model/pom.xml
pom.xml

Bump version spring-security to 5.2.1.RELEASE

Bump version dc-model to 4.0.3-SNAPSHOT

---

dc-model/src/main/java/de/digitalcollections/model/api/identifiable/entity/Entity.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/entity/EntityImpl.java

introducing short referencable id for making it possible to create short URLs like:
https://bsb.de/198776

Add short reference id and entity documentation

---

dc-model-jackson/pom.xml
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/entity/parts/WebpageFactory.java
dc-model-jackson/src/test/resources/serializedTestObjects/webpage.json
dc-model-xml/pom.xml
dc-model-xml/src/test/java/de/digitalcollections/model/xml/xstream/v1/WebpageFactory.java
dc-model-xml/src/test/resources/serializedTestObjects/v1Webpage.xml
dc-model/pom.xml
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/parts/structuredcontent/contentblocks/IFrameImpl.java
pom.xml

This PR adds a `title` attribute to the `iframe` contentblock.

Iframe title

---

dc-model-xml/src/main/java/de/digitalcollections/model/xml/xstream/DigitalCollectionsXStreamMarshaller.java
dc-model-xml/src/main/java/de/digitalcollections/model/xml/xstream/v1/V1DigitalCollectionsXStreamMarshaller.java
dc-model-xml/src/test/java/de/digitalcollections/model/xml/xstream/WebpageFactory.java
dc-model-xml/src/test/java/de/digitalcollections/model/xml/xstream/WebpageTest.java
dc-model-xml/src/test/resources/serializedTestObjects/webpage.xml

This PR adds some more xml aliases for java classes.

Add more xml aliases for classes

---

dc-model/src/main/java/de/digitalcollections/model/api/identifiable/resource/MimeType.java
dc-model/src/test/java/de/digitalcollections/model/api/identifiable/resource/MimeTypeTest.java

Fix mimetype "image/*": It is not detected as known type and method "fromTypename(String typeName)" returned null.

Fix mimetype "image/*".

---

dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/DigitalCollectionsModelModule.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/paging/SearchPageRequestMixIn.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/paging/SearchPageResponseMixIn.java
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/paging/SearchPageRequestTest.java
dc-model/src/main/java/de/digitalcollections/model/api/paging/SearchPageRequest.java
dc-model/src/main/java/de/digitalcollections/model/api/paging/SearchPageResponse.java
dc-model/src/main/java/de/digitalcollections/model/impl/paging/SearchPageRequestImpl.java
dc-model/src/main/java/de/digitalcollections/model/impl/paging/SearchPageResponseImpl.java

basic search model for paged simple search request/response. needed for simple autocompletion

Add basic search page request/response model (simple search with paging)

---

dc-model-feign/pom.xml
dc-model-jackson/pom.xml
pom.xml

versions upgraded and dc-model tested with cudami

Bump version of jackson, assertj-core and feign-core

---

dc-model-feign/pom.xml
dc-model-jackson/pom.xml
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/paging/PageResponseMixIn.java
dc-model-xml/pom.xml
dc-model/pom.xml
pom.xml

This PR changes the serialized json of a page response - the type information about the content list entries is not anymore serialized as wrapper around the real object, it is serialized as property of the real object.
Before the json of e.g. the endpoint `/latest/webpages` looked like this:
```
{
"content": [
{
"de.digitalcollections.model.impl.identifiable.entity.parts.WebpageImpl": {
"created": "2020-05-14T12:28:43.63549",
"identifiers": [],
"label": {
"de": "My webpage"
},
"lastModified": "2020-05-14T12:28:43.635497",
"type": "ENTITY_PART",
"uuid": "a2999a64-6dac-4bf3-937b-192e743034a8",
"entityPartType": "WEBPAGE",
"publicationStart": "2019-11-12"
}
}
],
"pageRequest": {
"pageNumber": 0,
"pageSize": 1,
"filtering": {
"filterCriterias": []
},
"sorting": {
"orders": [
{
"direction": …
```

Fix page response json

---

dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/resource/FileResourceImpl.java
dc-model/src/test/java/de/digitalcollections/model/impl/identifiable/resource/FileResourceImplTest.java

filename and extension contained requestparams string. fixed

Fix filenameextension

---

dc-model/src/main/java/de/digitalcollections/model/api/http/exceptions/HttpErrorDecoder.java
dc-model/src/main/java/de/digitalcollections/model/api/http/exceptions/client/UnprocessableEntityException.java

Add http error decoder used in http client libraries. add exception class for 422 code (UnprocessableEntityException)

Add http error decoder

---

dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/EntityMixIn.java
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/entity/EntityTest.java

This PR adds the serialization info for Corporations to the Entity mixin

Add corporation and project to entity mixin

---

dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/entity/work/ItemTest.java
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/entity/work/WorkTest.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/resource/FileResource.java

Add tests for item and work

---

dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/entity/CollectionTest.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/entity/Collection.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/entity/CollectionImpl.java

This PR adds publication dates to collections.

Collection publication dates

---

dc-model-feign/pom.xml
dc-model-jackson/pom.xml
dc-model-xml/pom.xml
dc-model/pom.xml
dc-model/src/main/java/de/digitalcollections/model/api/filter/Filtering.java
dc-model/src/main/java/de/digitalcollections/model/api/filter/enums/FilterOperation.java
pom.xml

For example a combination like:
"presentationEnd-Date should be greater than now or not be set."

More filter for "not set" combinations

---

dc-model/src/main/java/de/digitalcollections/model/api/filter/Filtering.java
dc-model/src/main/java/de/digitalcollections/model/api/paging/PageRequest.java
dc-model/src/main/java/de/digitalcollections/model/impl/filter/FilteringImpl.java

* add "add" for filtering
* rename "filtercriterias" to "filtercriteria"
* sorted members alphabetically

Add method "add" for adding/setting additional filtering

---

dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/entity/DigitalObjectTest.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/entity/Entity.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/entity/parts/CustomAttributes.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/entity/EntityImpl.java

Add custom attributes to Entity (inherits to all entities like digitalobject)

Add custom attributes to entity

---

dc-model/src/main/java/de/digitalcollections/model/api/filter/Filtering.java
dc-model/src/main/java/de/digitalcollections/model/api/filter/enums/FilterOperation.java

This PR adds two new filters `LESS_THAN_AND_SET` and `LESS_THAN_OR_EQUAL_TO_AND_SET`.

Add some more filter combinations with isset

---

dc-model-jackson/pom.xml

as it is used during compile time

Add wdtk-datamodel as direct dependency

---

dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/IdentifiableImpl.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/entity/CollectionImpl.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/entity/EntityImpl.java

`CollectionImpl` benötigt `equals` und `hashCode`

Added hashCode and equals for CollectionImpl

---

.github/workflows/ci.yml

Warum hattest du das entfernt, @stefan-it ?

Add job for publishing

---

dc-model/src/main/java/de/digitalcollections/model/api/identifiable/entity/Article.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/entity/enums/EntityType.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/entity/ArticleImpl.java

Add publication infos to article and add Geolocation type for upcoming project needs

Article extended

---

dc-model-xml/pom.xml
dc-model-xml/src/main/java/de/digitalcollections/model/xml/xstream/DigitalCollectionsXStreamMarshaller.java
dc-model-xml/src/main/java/de/digitalcollections/model/xml/xstream/v1/V1DigitalCollectionsXStreamMarshaller.java

Adding security fix according to advice: https://x-stream.github.io/CVE-2020-26217.html

Adding security fix for xstream

---

dc-model-feign/pom.xml
dc-model-jackson/pom.xml
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/DigitalCollectionsModelModule.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/view/RenderingTemplateMixIn.java
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/view/RenderingTemplateTest.java
dc-model-xml/pom.xml
dc-model/pom.xml
dc-model/src/main/java/de/digitalcollections/model/impl/view/RenderingTemplate.java
pom.xml

This PR adds a new model object for rendering templates.

Rendering templates

---

dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/DigitalCollectionsModelModule.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/view/RenderingHintsMixIn.java
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/view/RenderingHintsTest.java
dc-model/src/main/java/de/digitalcollections/model/api/identifiable/entity/parts/Webpage.java
dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/entity/parts/WebpageImpl.java
dc-model/src/main/java/de/digitalcollections/model/impl/view/RenderingHints.java

This PR adds rendering hints like a template name to a webpage.

Add rendering hints to webpage

---

dc-model/src/main/java/de/digitalcollections/model/api/paging/Order.java
dc-model/src/main/java/de/digitalcollections/model/api/paging/PageRequest.java
dc-model/src/main/java/de/digitalcollections/model/api/paging/PageResponse.java
dc-model/src/main/java/de/digitalcollections/model/api/paging/Sorting.java
dc-model/src/main/java/de/digitalcollections/model/impl/paging/OrderImpl.java
dc-model/src/main/java/de/digitalcollections/model/impl/paging/PageRequestImpl.java
dc-model/src/main/java/de/digitalcollections/model/impl/paging/PageResponseImpl.java
dc-model/src/main/java/de/digitalcollections/model/impl/paging/SortingImpl.java

This PR introduces a new method `hasSorting` and a filtering for `null` orders.

Sorting improvements

---

dc-model-jackson/pom.xml
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/alias/LocalizedUrlAliasesMixIn.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/alias/UrlAliasMixIn.java
dc-model/pom.xml
dc-model/src/main/java/de/digitalcollections/model/alias/LocalizedUrlAliases.java
dc-model/src/main/java/de/digitalcollections/model/alias/UrlAlias.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/Identifiable.java
pom.xml

Ticket: mdz/webapps/internal/cudami/-/issues/141

Add UrlAlias, LocalizedUrlAliases and their MixIns

---

dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/alias/LocalizedUrlAliasesMixIn.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/alias/UrlAliasMixIn.java
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/alias/LocalizedUrlAliasesTest.java
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/alias/UrlAliasTest.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/Identifiable.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/alias/LocalizedUrlAliases.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/alias/UrlAlias.java
dc-model/src/test/java/de/digitalcollections/model/identifiable/alias/LocalizedUrlAliasesTest.java

Ticket: [mdz/webapps/internal/cudami/-/issues/169]

Refactor packages of UrlAlias and LocalizedUrlAliases

---

dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/alias/UrlAliasTest.java
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/alias/LocalizedUrlAliases.json
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/alias/UrlAlias.json
dc-model/src/main/java/de/digitalcollections/model/identifiable/alias/UrlAlias.java
dc-model/src/test/java/de/digitalcollections/model/identifiable/alias/LocalizedUrlAliasesTest.java

Ticket: mdz/webapps/internal/cudami/-/issues/182

UrlAlias: Replace `websiteUuid` by `website` itself

---

CHANGELOG.md
dc-model-jackson/pom.xml
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/entity/DigitalObjectTest.java
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/entity/DigitalObject.json
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/entity/relation/EntityRelation.json
dc-model-jackson/src/test/resources/serializedTestObjects/paging/SearchPageResponse.json
dc-model/pom.xml
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/DigitalObject.java
dc-model/src/main/java/de/digitalcollections/model/production/CreationInfo.java
dc-model/src/main/java/de/digitalcollections/model/security/User.java
pom.xml

First prototype for the extended `DigitalObject`

Updated fields for DigitalObject

---

dc-model/src/main/java/de/digitalcollections/model/filter/FilterCriterion.java
dc-model/src/main/java/de/digitalcollections/model/filter/Filtering.java
dc-model/src/main/java/de/digitalcollections/model/paging/SearchPageRequest.java
dc-model/src/main/java/de/digitalcollections/model/text/StructuredContent.java

Add missing `equals` and `hashCode` methods for filtering search

Add missing equals / hashCode methods for filtering search

---

dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/paging/OrderMixIn.java
dc-model-jackson/src/test/resources/serializedTestObjects/list/ListRequest.json
dc-model/src/main/java/de/digitalcollections/model/filter/FilterCriterion.java

* Remove isascending/isdescending from json payload
* Remove validate() method call from set expression (not sure, why it was inserted, so delete it) and add default constructor (had complains by jackson)

Remove isascending/isdescending from json payload

---

dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/alias/LocalizedUrlAliases.json
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/alias/UrlAlias.json
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/entity/relation/EntityRelation.json
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/entity/work/Item.json
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/web/Webpage.json
dc-model-jackson/src/test/resources/serializedTestObjects/legal/License.json
dc-model-jackson/src/test/resources/serializedTestObjects/view/RenderingTemplate.json
dc-model/src/main/java/de/digitalcollections/model/UniqueObject.java
dc-model/src/main/java/de/digitalcollections/model/exception/http/HttpErrorDecoder.java
dc-model/src/main/java/de/digitalcollections/model/exception/http/HttpException.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/Identifiable.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/web/Webpage.java
dc-model/src/main/java/de/digitalcollections/model/legal/License.java
dc-model/src/main/java/de/digitalcollections/model/security/User.java
dc-model/src/main/java/de/digitalcollections/model/semantic/Headword.java
dc-model/src/main/java/de/digitalcollections/model/view/RenderingTemplate.java

Introduce abstract UniqueObject class for all unqiue objects identifiable by uuid and having attributes created and lastModified.
Needed for all objects not being an Identifiable or Entity but being a managed object (being persisted in own tables, having own endpoints, ...). Neede to bundle common attributes and behaviour (e.g. in rest clients and tests)
Sorry: also changed Exception classes are being commited: resulted in merging HttpExceptions from cudami into model.

Introduce abstract UniqueObject class

---

dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/IdentifierType.json
dc-model/src/main/java/de/digitalcollections/model/identifiable/Identifier.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/IdentifierType.java
dc-model/src/main/java/de/digitalcollections/model/relation/Predicate.java
dc-model/src/main/java/de/digitalcollections/model/security/User.java

Introduce UniqueObject for unique objects that now have created, lastModified and UUID

Introduce UniqueObject for unique objects

---

dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/alias/LocalizedUrlAliases.json
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/alias/UrlAlias.json
dc-model/src/main/java/de/digitalcollections/model/identifiable/Identifiable.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/alias/UrlAlias.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/alias/UrlAliasBuilder.java
dc-model/src/test/java/de/digitalcollections/model/identifiable/IdentifiableTest.java

Add convenience methode for retrieval of primary url aliases.

Convenience method for url aliases

---

dc-model/src/main/java/de/digitalcollections/model/filter/Filtering.java
dc-model/src/main/java/de/digitalcollections/model/text/StructuredContent.java

* Add `equals`/`hashCode` to `StructuredContent`, `FilterCriterion`, `Filtering` and `SearchPageRequest`
* Add `toString()` to `Filtering`

Filtering fixes

---

dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/DigitalObject.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/DigitalObjectBuilder.java

Resolve Warnings: Initialize new ArrayList with capacity 0

Replace ArrayList with List

---

dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/Article.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/HeadwordEntry.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/Topic.java

Fixes 20220511

---

dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/alias/LocalizedUrlAliases.json
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/alias/UrlAlias.json
dc-model/src/main/java/de/digitalcollections/model/identifiable/alias/UrlAlias.java
dc-model/src/test/java/de/digitalcollections/model/identifiable/alias/UrlAliasTest.java

Readd missing field `targetEntityType`.

Fix url alias

---

dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/entity/work/Item.json
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/work/Item.java

`holders` werden jetzt korrekt initialisiert

Fix item init

---

dc-model/src/main/java/de/digitalcollections/model/UniqueObject.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/alias/UrlAlias.java
dc-model/src/main/java/de/digitalcollections/model/time/TimestampHelper.java
dc-model/src/test/java/de/digitalcollections/model/time/TimestampHelperTest.java

...to run with Java 17 smoothly, see ticket.
Ticket: mdz/webapps/internal/cudami/-/issues/201

Add ``TimestampHelper`` to truncate ``LocalDateTime`` to microseconds

---

dc-model/src/main/java/de/digitalcollections/model/list/buckets/BucketsRequest.java

Rename bucketSize to numberOfBuckets

Add missing javadoc

---

dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/entity/work/ManifestationTest.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/relation/EntityRelation.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/work/Manifestation.java

Fix toString in manifestation

---

dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/entity/work/ManifestationTest.java
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/entity/work/Manifestation.json
dc-model/src/main/java/de/digitalcollections/model/RelationSpecification.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/work/Manifestation.java

Added parents (as list of RelationSpecification) and manifestationType; remove sortKey and series

Finished Manifestation

---

CHANGELOG.md
dc-model/src/main/java/de/digitalcollections/model/relation/Predicate.java
dc-model/src/main/java/de/digitalcollections/model/validation/ValidationError.java
dc-model/src/main/java/de/digitalcollections/model/validation/ValidationException.java

Add classes for server side validation exception
Change description to LocalizedStructuredContent analog to other objects

Validation

---

CHANGELOG.md
dc-model/src/main/java/de/digitalcollections/model/content/ManagedContent.java
dc-model/src/main/java/de/digitalcollections/model/content/PublicationStatus.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/Collection.java
dc-model/src/main/java/de/digitalcollections/model/time/TimeBasedState.java
dc-model/src/main/java/de/digitalcollections/model/time/TimeBasedStatus.java

- New models: Interface `ManagedContent` and Enumeration `PublicationStatus` for content being managed in a content management system and having different states of publication ("online visibility")
- `Collection` implements `ManagedContent` (has different publication stati)

Publication state

---

dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/Entity.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/web/Webpage.java

Add ManagedContent interface to Webpage for handling publication status

Managedcontent

---

dc-model/src/main/java/de/digitalcollections/model/time/TimeValue.java

Convenience method to instanciate a TimeValue with only year and month

Timevalue year and month

---

.gitignore
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/entity/manifestation/ManifestationTest.java
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/mixin/list/ListResponseMixInTest.java
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/mixin/list/paging/PageResponseMixInTest.java
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/semantic/TagTest.java
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/entity/manifestation/Manifestation.json
dc-model-jackson/src/test/resources/serializedTestObjects/list/ListResponse_Tag.json
dc-model-jackson/src/test/resources/serializedTestObjects/list/paging/PageResponse_Tag.json
dc-model-jackson/src/test/resources/serializedTestObjects/semantic/Tag.json
dc-model/src/main/java/de/digitalcollections/model/semantic/Tag.java

Rename tag name to value

---

dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/IdentifiableMixIn.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/EntityMixIn.java

Unfortunately, we use both, `GEOLOCATION` and `GEO_LOCATION`, and this for years, so we cannot harmonize them

Fixes (or better: hacks) Geolocation serialization

---

dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/UniqueObjectMixIn.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/alias/UrlAliasMixIn.java
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/alias/LocalizedUrlAliases.json
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/alias/UrlAlias.json
dc-model/src/main/java/de/digitalcollections/model/identifiable/alias/UrlAlias.java

- only model change: now has lastModified, too.
- change Builder to now use lombok and inherits builder from uniqueobject

Refactor UrlAlias to now extending UniqueObject

---

CHANGELOG.md
dc-model-jackson/pom.xml
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/UniqueObjectMixIn.java
dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/list/ListRequestMixIn.java
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/Identifier.json
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/IdentifierType.json
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/entity/DigitalObject.json
dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/entity/HeadwordEntry.json
dc-model-jackson/src/test/resources/serializedTestObjects/legal/License.json
dc-model-jackson/src/test/resources/serializedTestObjects/list/ListRequest.json
dc-model-jackson/src/test/resources/serializedTestObjects/list/ListResponse.json
dc-model-jackson/src/test/resources/serializedTestObjects/list/paging/PageRequest.json
dc-model-jackson/src/test/resources/serializedTestObjects/list/paging/PageResponse.json
dc-model-jackson/src/test/resources/serializedTestObjects/list/paging/PageResponse_differentTypes.json
dc-model-jackson/src/test/resources/serializedTestObjects/semantic/Headword.json
dc-model-jackson/src/test/resources/serializedTestObjects/view/RenderingTemplate.json
dc-model/pom.xml
pom.xml

Ticket: mdz/webapps/external/homepage/-/issues/1427

Fix 11.0.2 serialization

---

CHANGELOG.md
dc-model-jackson/pom.xml
dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/semantic/HeadwordTest.java
dc-model-jackson/src/test/resources/serializedTestObjects/semantic/Headword_normalized.json
dc-model-mappings/dc-model-html-mapping/pom.xml
dc-model-mappings/pom.xml
dc-model/pom.xml
dc-model/src/main/java/de/digitalcollections/model/semantic/Headword.java
pom.xml

Add normalized label field to headword
Bump version to 12.1.0-SNAPSHOT

Normalized label field to headword

---

dc-model-jackson/pom.xml
dc-model-mappings/dc-model-html-mapping/pom.xml
dc-model-mappings/pom.xml
dc-model/pom.xml
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/geo/location/Canyon.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/geo/location/Cave.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/geo/location/Continent.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/geo/location/Country.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/geo/location/Creek.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/geo/location/HumanSettlement.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/geo/location/Lake.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/geo/location/Mountain.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/geo/location/Ocean.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/geo/location/River.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/geo/location/Sea.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/geo/location/StillWaters.java
dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/geo/location/Valley.java
pom.xml

- Add builders to geo location classes (just existed for HumanSettlement)
- Bump version to 12.2.0-SNAPSHOT

Add builders to geo location classes
