- .travis.yml
PR adds `openjdk11` to Travis CI build matrix :tada:
> Travis CI: OpenJDK 11

- pom.xml
This PR adds `jacoco` for code coverage. It also enables `codecov` information on GitHub.
> Add jacoco integration

- dc-model-jackson/pom.xml
This PR updates the version of `jackson` to fix CVE-2018-19360, CVE-2018-19362 and CVE-2018-19361.
This was found during a GitHub Security Scan.
> Security alert: update version of jackson

- dc-model-jackson/pom.xml
- dc-model-xml/pom.xml
- dc-model/pom.xml
- pom.xml
This PR updates the  `junit-jupiter` and `maven-surefire-plugin` dependencies.
`junit-jupiter` meta package is used instead of `junit-jupiter-api`.
> JUnit updates

- dc-model-jackson/pom.xml
- dc-model-xml/pom.xml
- dc-model/pom.xml
- dc-model/src/main/java/de/digitalcollections/model/api/identifiable/parts/LocalizedText.java
- dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/parts/LocalizedTextImpl.java
- pom.xml
This PR fixes the return type of the method `getLocales` in the `LocalizedText` class to `ArrayList`.
> Fix return type

- dc-model-jackson/pom.xml
- dc-model-xml/pom.xml
- dc-model/pom.xml
- dc-model/src/main/java/de/digitalcollections/model/api/identifiable/resource/MimeType.java
- pom.xml
Heavyweight dependencies such as Guava should only be used in libraries
when really necessary. In this case the Java 11 stream API can be used
as complete replacement.
Fixes #101 (Dependabot Guava upgrade).
> Remove Guava as production dependency

- dc-model-jackson/pom.xml
- dc-model-xml/pom.xml
- dc-model/pom.xml
- dc-model/src/main/java/de/digitalcollections/model/api/identifiable/Identifiable.java
- dc-model/src/main/java/de/digitalcollections/model/api/identifiable/entity/DigitalObject.java
- dc-model/src/main/java/de/digitalcollections/model/api/identifiable/entity/parts/ContentNode.java
- dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/IdentifiableImpl.java
- dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/IdentifierImpl.java
- dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/entity/DigitalObjectImpl.java
- dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/entity/parts/ContentNodeImpl.java
- dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/resource/FileResourceImpl.java
- pom.xml
- Replace LinkedHashSet with List for ordered lists
- Replace List with Set for unordered Lists without duplicates
- add hashCode and equals where needed
- Bump version to 6.0.0-SNAPSHOT as it is a API/breaking change
- fixes #44
> Replace LinkedHashSet with List

- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/resource/FileResourceMixIn.java
- dc-model/src/main/java/de/digitalcollections/model/api/identifiable/resource/enums/FileResourceType.java
- dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/resource/FileResourceImpl.java
For list of all fileresources every file resource is just filled with needed core properties of fileresource, no fileresource specific fields are filled. This merge request makes it possible to get such a generic list (with serializing and deserializing)
> Add generic fileresource type (undefined)

- dc-model/src/main/java/de/digitalcollections/model/api/identifiable/resource/MimeType.java
- dc-model/src/test/java/de/digitalcollections/model/api/identifiable/resource/MimeTypeTest.java
Fix erroneous extension for mimetypes without given extensions. Now extensions are empty if no extension is in dc.mime.types
> Fix erroneous extension for mimetypes without given extensions

- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/DigitalCollectionsModelModule.java
- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/resource/RenderingHintsPreviewImageMixIn.java
- dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/resource/RenderingHintsImageTest.java
- dc-model/src/main/java/de/digitalcollections/model/api/identifiable/Identifiable.java
- dc-model/src/main/java/de/digitalcollections/model/api/identifiable/parts/RenderingHintsPreviewImage.java
- dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/IdentifiableImpl.java
- dc-model/src/main/java/de/digitalcollections/model/impl/identifiable/parts/RenderingHintsPreviewImageImpl.java
For rendering a preview image (e.g. use case: news with image) it is necessary to add some rendering information to the preview image supporting accessibility rules (alt, title) and optional caption and target link (in new window or same). This has to be stored separate from image that can be used in different places with different rendering hints.
This pull request adds an object containing rendering hints and adds it beside preview image to every identifiable (already having preview image)
> Add rendering hints object for preview image of an identifiable

- dc-model/src/main/java/de/digitalcollections/model/api/paging/Order.java
- dc-model/src/main/java/de/digitalcollections/model/impl/paging/OrderImpl.java
This PR adds an optional sub property to order for, can be used for e.g. a key in a jsonb column.
> Add sub property to order for

- dc-model/src/main/java/de/digitalcollections/model/api/filter/FilterValuePlaceholder.java
New class for handling filter values that should not be parsed (e.g: use ":uuid" as is and do not wrap single quotes around it in sql)
> Add FilterValuePlaceholder

- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/paging/PageResponseMixIn.java
- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/view/BreadcrumbNavigationMixIn.java
- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/view/RenderingHintsMixIn.java
- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/view/RenderingHintsPreviewImageMixIn.java
- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/view/RenderingTemplateMixIn.java
- dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/BaseJsonSerializationTest.java
- dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/paging/SearchPageResponseTest.java
- dc-model-jackson/src/test/resources/serializedTestObjects/paging/PageResponse.json
- dc-model-jackson/src/test/resources/serializedTestObjects/paging/SearchPageResponse.json
- Type info (Field `type`) also for non-resources and non-entities
- Type info (Field `objectType`) for content objects in page responses
> Serialization fixes

- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/alias/LocalizedUrlAliasesMixIn.java
- dc-model/src/main/java/de/digitalcollections/model/alias/LocalizedUrlAliases.java
- dc-model/src/test/java/de/digitalcollections/model/alias/LocalizedUrlAliasesTest.java
...with an own `equals` and two more handy methods. By the way an unittest is added.
> Extend LocalizedUrlAliases model

- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/DigitalCollectionsModelModule.java
- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/list/ListRequestMixIn.java
- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/list/ListResponseMixIn.java
- dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/list/ListRequestTest.java
- dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/list/ListResponseTest.java
- dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/paging/SearchPageResponseTest.java
- dc-model-jackson/src/test/resources/serializedTestObjects/list/ListRequest.json
- dc-model-jackson/src/test/resources/serializedTestObjects/list/ListResponse.json
- dc-model-jackson/src/test/resources/serializedTestObjects/paging/SearchPageResponse.json
- dc-model/src/main/java/de/digitalcollections/model/list/ListRequest.java
- dc-model/src/main/java/de/digitalcollections/model/list/ListResponse.java
- dc-model/src/main/java/de/digitalcollections/model/paging/Order.java
- dc-model/src/main/java/de/digitalcollections/model/paging/PageRequest.java
- dc-model/src/main/java/de/digitalcollections/model/paging/PageResponse.java
- dc-model/src/main/java/de/digitalcollections/model/paging/SearchPageResponse.java
- add ListRequest as parent to PageRequest (without paging params) (for full list)
- add ListResponse as parent to PageResponse (without paging params) (for full list)
- rename "sort" field to "sorting"
- Set query field in SearchPageResponse to deprecated (close issue #215 )
no compile problems in cudami (using this library)
> Add listrequest and listresponse

- dc-model/src/main/java/de/digitalcollections/model/identifiable/alias/LocalizedUrlAliases.java
- dc-model/src/test/java/de/digitalcollections/model/identifiable/alias/LocalizedUrlAliasesTest.java
Currently two `LocalizedUrlAliases` objects that are extending `Map` are compared by using Map's `equals` method. This leads to a list comparison where the order of the entries matters (of course, because lists consider their sorting). However, we do not care about the sorting. It only matters that the objects contain equal `UrlAlias` objects. This PR implements the desired behaviour.
> Fix `equals` in LocalizedUrlAliases

- dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/DigitalObject.java
- dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/Entity.java
navDate is a generally useful field for all entities, especially work, item, manifestation, digitalobject. as it is an optional field it can be empty depending on usecase.
> Move navDate to Entity

- CHANGELOG.md
- dc-model-jackson/pom.xml
- dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/identifiable/entity/work/ItemTest.java
- dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/entity/work/Item.json
- dc-model/pom.xml
- dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/work/Item.java
- pom.xml
Removed obsolete fields `language`, `publicationDate`,`publicationPlace`, `publisher` and `version` in `Item` since they belong to the Manifestation/Expression.
> Breaking change: Removed obsolete/wrong fields in Item

- .gitignore
- CHANGELOG.md
- dc-model-mappings/dc-model-html-mapping/pom.xml
- dc-model-mappings/dc-model-html-mapping/src/main/java/de/digitalcollections/model/mappings/html/HtmlMapper.java
- dc-model-mappings/dc-model-html-mapping/src/test/java/de/digitalcollections/model/mappings/html/HtmlMapperTest.java
- dc-model-mappings/pom.xml
- dc-model/src/main/java/de/digitalcollections/model/identifiable/Identifiable.java
- pom.xml
- adds module "mapping" with submodule "html" for mapping HTML code (currently supporting ul, li, a) to DC-Model StructuredContent
- add convenience method addLocalizedUrlAlias(UrlAlias urlAlias) to Identifiable
> Mapping module

- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/manifestation/DistributionInfoMixIn.java
- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/manifestation/ProductionInfoMixIn.java
- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/manifestation/PublicationInfoMixIn.java
- dc-model-jackson/src/main/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/manifestation/PublisherMixIn.java
- dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/manifestation/DistributionInfoMixInTest.java
- dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/manifestation/ProductionInfoMixInTest.java
- dc-model-jackson/src/test/java/de/digitalcollections/model/jackson/mixin/identifiable/entity/manifestation/PublicationInfoMixInTest.java
- dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/entity/manifestation/DistributionInfo.json
- dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/entity/manifestation/Manifestation.json
- dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/entity/manifestation/ProductionInfo.json
- dc-model-jackson/src/test/resources/serializedTestObjects/identifiable/entity/manifestation/PublicationInfo.json
- dc-model/src/main/java/de/digitalcollections/model/identifiable/entity/manifestation/Publisher.java
- `Publisher` is no longer a UniqueObject
- Removed serialization of `empty` flag of `PublishingInfo` derivatives
> publisher-related fixes

- CHANGELOG.md
- dc-model/src/main/java/de/digitalcollections/model/list/filtering/FilterCriterion.java
- dc-model/src/main/java/de/digitalcollections/model/list/filtering/FilterOperation.java
…and expand FilterCriterion builder
> Add regexp filter operations
